---
# Specify the line length that the printer will wrap on.
printWidth: 80

# Specify the number of spaces per indentation-level.
tabWidth: 4

# Indent lines with tabs instead of spaces.
useTabs: true

# Print semicolons at the ends of statements.
semi: true

# Use single quotes instead of double quotes.
singleQuote: false

# Change when properties in objects are quoted.
quoteProps: as-needed

# Use single quotes instead of double quotes in JSX.
jsxSingleQuote: false

# Print trailing commas wherever possible when multi-line.
trailingComma: all

# Print spaces between brackets in object literals.
bracketSpacing: false

# Put the > of a multi-line JSX element at the end of the last line instead of being alone on the next line (does not apply to self closing elements).
jsxBracketSameLine: false

# Include parentheses around a sole arrow function parameter.
arrowParens: always

# Prettier can restrict itself to only format files that contain a special comment, called a pragma, at the top of the file.
requirePragma: false

# Prettier can insert a special @format marker at the top of files specifying that the file has been formatted with prettier.
insertPragma: false

# By default, Prettier will wrap markdown text as-is since some services use a linebreak-sensitive renderer, e.g. GitHub comment and BitBucket. In some cases you may want to rely on editor/viewer soft wrapping instead, so this option allows you to opt out with "never".
proseWrap: preserve

# Specify the global whitespace sensitivity for HTML files, see whitespace-sensitive formatting for more info.
htmlWhitespaceSensitivity: css

# Whether or not to indent the code inside <script> and <style> tags in Vue files.
vueIndentScriptAndStyle: true

# End of Line
endOfLine: auto
